export const COMPANY_GET_ALL_REQUEST = "COMPANY_GET_ALL_REQUEST";
export const C0MPANY_GET_ALL_SUCCESS = "C0MPANY_GET_ALL_SUCCESS";
export const COMPANY_GET_ALL_FAIL = "COMPANY_GET_ALL_FAIL";

export const COMPANY_GET_ONE_REQUEST = "COMPANY_GET_ONE_REQUEST";
export const C0MPANY_GET_ONE_SUCCESS = "C0MPANY_GET_ONE_SUCCESS";
export const COMPANY_GET_ONE_FAIL = "COMPANY_GET_ONE_FAIL";

export const COMPANY_MODIFY_ONE_REQUEST = "COMPANY_MODIFY_ONE_REQUEST";
export const COMPANY_MODIFY_ONE_SUCCESS = "COMPANY_MODIFY_ONE_SUCCESS";
export const COMPANY_MODIFY_ONE_FAIL = "COMPANY_MODIFY_ONE_FAIL";

export const C0MPANY_FOLLOW_ONE_SUCCESS = "C0MPANY_FOLLOW_ONE_SUCCESS";
export const C0MPANY_FOLLOW_ONE_FAIL = "C0MPANY_FOLLOW_ONE_FAIL";

export const C0MPANY_UNFOLLOW_ONE_SUCCESS = "C0MPANY_UNFOLLOW_ONE_SUCCESS";
export const C0MPANY_UNFOLLOW_ONE_FAIL = "C0MPANY_UNFOLLOW_ONE_FAIL";
