export const JOB_GET_ALL_REQUEST = "JOB_GET_ALL_REQUEST";
export const JOB_GET_ALL_SUCCESS = "JOB_GET_ALL_SUCCESS";
export const JOB_GET_ALL_FAIL = "JOB_GET_ALL_FAIL";

export const JOB_GET_ONE_REQUEST = "JOB_GET_ONE_REQUEST";
export const JOB_GET_ONE_SUCCESS = "JOB_GET_ONE_SUCCESS";
export const JOB_GET_ONE_FAIL = "JOB_GET_ONE_FAIL";
