export const MESSAGE_GET_ALL_REQUEST = "MESSAGE_GET_ALL_REQUEST";
export const MESSAGE_GET_ALL_SUCCESS = "MESSAGE_GET_ALL_SUCCESS";
export const MESSAGE_GET_ALL_FAIL = "MESSAGE_GET_ALL_FAIL";

export const MESSAGE_GET_ONE_REQUEST = "MESSAGE_GET_ONE_REQUEST";
export const MESSAGE_GET_ONE_SUCCESS = "MESSAGE_GET_ONE_SUCCESS";
export const MESSAGE_GET_ONE_FAIL = "MESSAGE_GET_ONE_FAIL";

export const MESSAGE_SEND_ONE_REQUEST = "MESSAGE_SEND_ONE_REQUEST";
export const MESSAGE_SEND_ONE_SUCCESS = "MESSAGE_SEND_ONE_SUCCESS";
export const MESSAGE_SEND_ONE_FAIL = "MESSAGE_SEND_ONE_FAIL";

export const MESSAGE_DELETE_ONE_REQUEST = "MESSAGE_DELETE_ONE_REQUEST";
export const MESSAGE_DELETE_ONE_SUCCESS = "MESSAGE_DELETE_ONE_SUCCESS";
export const MESSAGE_DELETE_ONE_FAIL = "MESSAGE_DELETE_ONE_FAIL";

export const MESSAGE_DELETE_CONVERSATION_REQUEST =
  "MESSAGE_DELETE_CONVERSATION_REQUEST";
export const MESSAGE_DELETE_CONVERSATION_SUCCESS =
  "MESSAGE_DELETE_CONVERSATION_SUCCESS";
export const MESSAGE_DELETE_CONVERSATION_FAIL =
  "MESSAGE_DELETE_CONVERSATION_FAIL";

export const MESSAGE_CLOSE_ACTIVE_BUBBLE = "MESSAGE_CLOSE_ACTIVE_BUBBLE";
