export const RESUME_GET_ALL_REQUEST = "RESUME_GET_ALL_REQUEST";
export const RESUME_GET_ALL_SUCCESS = "RESUME_GET_ALL_SUCCESS";
export const RESUME_GET_ALL_FAIL = "RESUME_GET_ALL_FAIL";

export const RESUME_GET_ONE_REQUEST = "RESUME_GET_ONE_REQUEST";
export const RESUME_GET_ONE_SUCCESS = "RESUME_GET_ONE_SUCCESS";
export const RESUME_GET_ONE_FAIL = "RESUME_GET_ONE_FAIL";

export const RESUME_DOWNLOAD_ONE_REQUEST = "RESUME_DOWNLOAD_ONE_REQUEST";
export const RESUME_DOWNLOAD_ONE_DONE = "RESUME_DOWNLOAD_ONE_DONE";

export const RESUME_CREATE_REQUEST = "RESUME_CREATE_REQUEST";
export const RESUME_CREATE_SUCCESS = "RESUME_CREATE_SUCCESS";
export const RESUME_CREATE_FAIL = "RESUME_CREATE_FAIL";

export const RESUME_UPDATE_REQUEST = "RESUME_UPDATE_REQUEST";
export const RESUME_UPDATE_SUCCESS = "RESUME_UPDATE_SUCCESS";
export const RESUME_UPDATE_FAIL = "RESUME_UPDATE_FAIL";
