export const ROUTES = {
  home: "/",
  profile: "/profile/:id",
  search: "/search",
  jobs: "/jobs",
  myJobs: "/jobs/my-jobs",
  job: "/jobs/:id",
  companies: "/company",
  myCompanies: "/company/mine",
  myCompaniesCreate: "/company/mine/create",
  myCompaniesUpdate: "/company/mine/:id",
  company: "/company/:id",
  talent: "/talent",
  talentfind: "/talent/post",
  resume: "/resume",
  resumeUpdate: "/resume/:id",
  jobApplicants: "/talent/post/:id/applicants",
  jobUpdate: "/talent/post/:id/update",
  messages: "/messages",
  authen: "/authen",
  forgot: "/authen/forgot",
};
