export const ROUTES = {
  home: "/",
  profile: "/profile/:id",
  jobs: "/jobs",
  myJobs: "/jobs/my-jobs",
  job: "/jobs/:id",
  companies: "/company",
  company: "/company/:id",
  talent: "/talent",
  talentfind: "/talent/post",
  resume: "/resume",
  resumeUpdate: "/resume/:id",
  jobUpdate: "/talent/post/:id/update",
  messages: "/messages",
  authen: "/authen",
  forgot: "/authen/forgot",
};
