export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAIL = "USER_INFO_FAIL";

export const USER_SEND_REQ_SUCCESS = "USER_SEND_REQ_SUCCESS";
export const USER_SEND_REQ_FAIL = "USER_SEND_REQ_FAIL";

export const USER_ACCEPT_SUCCESS = "USER_ACCEPT_SUCCESS";
export const USER_ACCEPT_FAIL = "USER_ACCEPT_FAIL";

export const USER_DELETE_REQ_SUCCESS = "USER_DELETE_REQ_SUCCESS";
export const USER_DELETE_REQ_FAIL = "USER_DELETE_REQ_FAIL";

export const USER_DELETE_FRIEND_SUCCESS = "USER_DELETE_FRIEND_SUCCESS";
export const USER_DELETE_FRIEND_FAIL = "USER_DELETE_FRIEND_FAIL";
